name: Sync README with Docs Repo

on: workflow_dispatch
permissions:
  contents: write

jobs:
  sync-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clone Docs Repository
        run: |
          git config --global user.name "shubhamp-sf"
          git config --global user.email "shubham.prajapat@sourcefuse.com"
          git clone https://github.com/shubhamp-sf/arc-docs.git docs-repo
          git config --list
        env:
          GITHUB_TOKEN: ${{ secrets.T_GITHUB_TOKEN }}

      - name: Sync README
        run: |
          extension_branch="automated/$(basename $GITHUB_REPOSITORY)-sync"
          cd docs-repo
          echo $extension_branch

          # Create a new branch if it doesn't exist, or switch to it if it does
          git checkout -B $extension_branch || git checkout $extension_branch

          # Copy README from the extension repo
          cp ../README.md docs/arc-api-docs/extensions/$(basename $GITHUB_REPOSITORY)/

          # Commit and push changes
          git add .
          git commit -m "Sync README with $(basename $GITHUB_REPOSITORY) repository"
          git config --list
          git push --force origin $extension_branch
        env:
          GITHUB_TOKEN: ${{ secrets.T_GITHUB_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.T_GITHUB_TOKEN }}
          branch: automated/$(basename $GITHUB_REPOSITORY)-sync
          base: main # Change this to match your default branch in the docs repo
          title: 'Sync README with $(basename $GITHUB_REPOSITORY) repository'
          body: 'This pull request automatically syncs the README with $(basename $GITHUB_REPOSITORY) repository.'
